[pytest]
#失败重跑核心配置
addopts = -v -s --reruns 2 --reruns-delay 1
#解释：
#--reruns 2：用例失败后重试2次
#--reruns-delay 1：重试间隔1秒（避免接口限流）

#测试文件匹配规则
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*


#禁用警告
filterwarnings = ignore::DeprecationWarning